### ISSUE TITLE
metrics?

### ISSUE THREAD

**Issue by building39** [epgsql/pooler#51]
I can't seem to get folsom to report metrics for pooler. folsom is on and running - I can get folsom_vm_metrics from my application's console, but nothing for pooler. Any idea what I
may be missing?

Here's the content of my sys.config:

 {pooler,
    [
      {pools,
        [
          [
            {name, riak_pool},
            {group, riak},
            {max_count, 500},
            {init_count, 20},
            {start_mfa, {riakc_pb_socket, start_link, ["nebriak1", 8087]}},
              %% if you want to enable metrics, set this to a module with
              %% an API conformant to the folsom_metrics module.
              %% If this config is missing, then no metrics are sent.
              {metrics_module, folsom_metrics}
          ]
        ]
      }
    ]
  }

**Comment by seriyps** [comment]
Closing as outdated. Fel free to reopen if disagree.
