### ISSUE TITLE
pooler:time_as_{millis, micro}/2 tests break with rebar3 on R15B03-1

### ISSUE THREAD

**Issue by sata** [epgsql/pooler#68]
from #66:

> Travis is failing test cases on R15B03-1, which seems to be related to rebar3 mess (I'm guessing it's not loading paths correctly since it cannot find pooler:time_as_{millis, micro}/2). I'm a strong advocate of using build tools which are agnostic to what OTP version your system is running. A build tool shouldn't change behaviour depending on what target you're aiming for.

What is the benefit of running rebar3 for a dependency project such as Pooler? This project has only edown as a dependency and Pooler isn't doing any advanced project management that requires Rebar3. So why not go with a build tool that's small, doesn't rely on specific OTP versions to work correctly and which also can be used in as many projects as possible? 

For example erlang.mk, as far as I know rebar3 will invoke _make_ for projects that aren't rebar3. Even if it doesn't,  we can generate a rebar.config[1] and keep it in the project. This _should_ work fine with erlang.mk based projects and rebar and as well with any other build tool which invokes _make_.

I'm currently tinkering with this but would like to hear what peoples' opinions are about it. 

[1] https://erlang.mk/guide/compat.html 11.2

**Comment by tsloughter** [comment]
rebar3 will not invoke make for projects at all -- unless specifically configured to do so in the `rebar.config` with a hook.

And note that `erlang.mk` has a lot of Erlang code in it and its plugins. So saying it is agnostic to the OTP version is wrong. It likely does less (I don't think it uses https for fetching deps for example) so may work with more OTP versions, but that is different from saying it is agnostic.

The prebuilt rebar3 escript is built using OTP 16 and we don't officially 'support' anything older than that.

Benefits for using rebar3 are the same whether a project is a "dependency project" or anything else. No matter the type of project you are going to be running tests and dialyzer and creating docs, possibly making use of profiles for those and if you have any dependencies then the dependency tracking (switch branches to a branch with a diff version dep and it'll fetch it/rebuild) and upgrading is useful.

**Comment by seriyps** [comment]
I'm closing it as outdated. Please reopen if you disagree.
