### ISSUE TITLE
erlang/otp 20 , pooler 1.5.2, can not compile

### ISSUE THREAD

**Issue by 221V** [epgsql/pooler#76]
==> "pooler"
Compiling /deps/pooler/src/pooler.erl
Line 20: error {undefined_type,{dict,0}} in "/deps/pooler/src/pooler.hrl"
Line 21: error {undefined_type,{queue,0}} in "/deps/pooler/src/pooler.hrl"
ERROR: []
escript: exception error: no function clause matching 
                 lists:flatten({return,{return,[{error,[]}]}}) (lists.erl, line 616)

**Comment by Oniry** [comment]
it seems the compatibility problem is not with erlang but with https://github.com/synrc/mad

https://github.com/silviucpp/mysql_pool/issues/3

**Comment by 221V** [comment]
https://github.com/221V/pooler/commits/master 
this fix works
mad is ok
